image:
  repository: mattfarina/query-store-quay-logs
  tag: 0.0.1
  pullPolicy: IfNotPresent

## cronjob history
successfulJobsHistoryLimit: 5
failedJobsHistoryLimit: 5

## set to `now` to get a one time job, or a cronjob schedule like `0 0 * * *`
## to get a cronjob.
schedule: "0/5 * * * *"
# schedule: now

# The secret information that should be injected into the application.
# These are all required values.
secrets:
  quayToken:
  azureStorageAccount:
  azureStorageAccessKey:
  container: