apiVersion: v1
kind: Secret
metadata:
  name: {{ template "query-store-quay-logs.fullname" . }}
  labels:
    app: {{ template "query-store-quay-logs.name" . }}
    chart: {{ template "query-store-quay-logs.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  quay-token: {{ default "" .Values.secrets.quayToken | b64enc | quote }}
  azure-storage-account: {{ default "" .Values.secrets.azureStorageAccount | b64enc | quote }}
  azure-storage-access-key: {{ default "" .Values.secrets.azureStorageAccessKey | b64enc | quote }}
  container: {{ default "" .Values.secrets.container | b64enc | quote }}